### ISSUE TITLE
Need REST endpoint for SAML configuration

### ISSUE THREAD

**Issue by brettaufheber** [aservo/confapi-confluence-plugin#74]
There is a plugin that allows SAML single sign-on for Atlassian data center applications. Unfortunately it is not possible to configure this plugin via a REST interface but I want to be able to do my SAML configuration for Confluence this way.

Plugin: SSO for Atlassian Data Center
Minimal supported version requirement: 4.1.10
Link: https://marketplace.atlassian.com/apps/1216096/sso-for-atlassian-server-and-data-center?hosting=datacenter&tab=overview

**Comment by pathob** [comment]
The existing but undocumented REST API `/rest/authconfig/1.0/...` probably is what you need.
